pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "yerkegal/experta-ci-demo"
    GIT_REPO_URL = "https://github.com/Yerkegal/Experta.git"
  }

  stages {
    stage('Checkout') {
      steps {
        git url: env.GIT_REPO_URL, branch: 'main'
      }
    }

    stage('Install & Test') {
      steps {
        dir('expetra-ci-demo') {
          sh 'python -m pip install -r requirements.txt'
          sh 'pytest -q'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('expetra-ci-demo') {
          sh "docker build -t ${env.DOCKER_IMAGE}:${env.BUILD_NUMBER} ."
        }
      }
    }

    stage('Push to Docker Hub') {
      when { branch 'main' }
      steps {
        withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login -u yerkegal --password-stdin'
          sh "docker tag ${env.DOCKER_IMAGE}:${env.BUILD_NUMBER} ${env.DOCKER_IMAGE}:latest"
          sh "docker push ${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}"
          sh "docker push ${env.DOCKER_IMAGE}:latest"
        }
      }
    }
  }
}
